/**
 * Regenerates `docs/state-diagram.md` from the engine's XState
 * machine. Run via:
 *
 *   pnpm --filter @mahjong/game-logic diagram
 *
 * The script writes the file directly via `fs.writeFileSync` rather
 * than dumping to stdout for shell redirection — pnpm's "running
 * script:" banner on some platforms (notably Windows) would otherwise
 * get captured into the committed file, leaving stale lines like
 * `> @mahjong/game-logic@0.0.0 diagram C:\Users\...` at the top.
 */
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { toDirectedGraph } from '@xstate/graph';
import { mahjongMachine } from '../src/machine.js';

interface Edge {
  from: string;
  to: string;
  label: string;
}

const graph = toDirectedGraph(mahjongMachine);

function collectStates(node: ReturnType<typeof toDirectedGraph>, into: Set<string>): void {
  into.add(node.id);
  for (const child of node.children) collectStates(child, into);
}

function collectEdges(node: ReturnType<typeof toDirectedGraph>, into: Edge[]): void {
  for (const e of node.edges) {
    if (!e.target) continue;
    const label = e.label?.text ?? '';
    into.push({ from: e.source.id, to: e.target.id, label });
  }
  for (const child of node.children) collectEdges(child, into);
}

const states = new Set<string>();
collectStates(graph, states);
const edges: Edge[] = [];
collectEdges(graph, edges);

// Mermaid expects state ids to match a few syntax constraints — strip
// the leading machine prefix so nodes read as `waiting`, `turn`, etc.
const strip = (id: string): string => {
  const last = id.split('.').pop() ?? id;
  return last;
};

const lines: string[] = ['# Engine state diagram', '', '```mermaid', 'stateDiagram-v2'];

// Initial state pointer.
lines.push(`    [*] --> ${strip(`${graph.id}.${graph.stateNode.config.initial ?? ''}`)}`);

// Top-level states (immediate children of root).
for (const child of graph.children) {
  const name = strip(child.id);
  if (child.children.length > 0) {
    // Compound state — render its child sub-diagram.
    lines.push(`    state ${name} {`);
    if (child.stateNode.config.initial) {
      lines.push(`        [*] --> ${child.stateNode.config.initial}`);
    }
    for (const sub of child.children) {
      const subName = strip(sub.id);
      lines.push(`        ${subName}`);
    }
    lines.push('    }');
  } else {
    lines.push(`    ${name}`);
  }
}

// Transitions. Always rules show as eventless (`∅`); their guard is
// included in brackets so the diagram explains *why* the always fires.
for (const e of edges) {
  // Skip self-loops on the same state — they clutter the diagram and
  // are implied by the `always` re-route rules.
  if (strip(e.from) === strip(e.to)) continue;
  lines.push(`    ${strip(e.from)} --> ${strip(e.to)}: ${e.label}`);
}

lines.push('```');
lines.push('');
lines.push('_Generated by `pnpm --filter @mahjong/game-logic diagram`._');

const here = dirname(fileURLToPath(import.meta.url));
const target = resolve(here, '../../../docs/state-diagram.md');
writeFileSync(target, `${lines.join('\n')}\n`);
process.stdout.write(`Wrote ${target}\n`);
