import type { CapacitorConfig } from '@capacitor/cli';

// Keep this in sync with SURFACE_BG in src/native/theme.ts. It's inlined
// here rather than imported because the Capacitor CLI parses this config
// with plain CJS require, which doesn't honor TS's `.js`→`.ts` resolution.
const SURFACE_BG = '#0e1320';

/**
 * Capacitor configuration for the Modern Mahjong shells. The native shells
 * (`apps/client/{ios,android}`) are gitignored and regenerated by CI on
 * every Android APK build via `npx cap add android`. The web bundle output
 * goes to `dist/` (Vite's default) and Capacitor syncs it into the native
 * shells on build.
 */
const config: CapacitorConfig = {
  appId: 'com.modernmahjong.app',
  appName: 'Modern Mahjong',
  webDir: 'dist',
  server: {
    androidScheme: 'https',
    // Required for LAN host URLs (http://192.168.x.x); production online play uses https.
    cleartext: true,
  },
  plugins: {
    SplashScreen: {
      backgroundColor: SURFACE_BG,
      showSpinner: false,
      launchAutoHide: true,
    },
    StatusBar: {
      style: 'DARK',
      backgroundColor: SURFACE_BG,
      overlaysWebView: false,
    },
  },
  ios: {
    contentInset: 'always',
  },
  android: {
    backgroundColor: SURFACE_BG,
  },
};

export default config;
